fsd

diff --git a/.github/workflows/go-ci.yml b/.github/workflows/go-ci.yml
--- a/.github/workflows/go-ci.yml
+++ b/.github/workflows/go-ci.yml
@@ -52,6 +52,14 @@ jobs:
         # working-directory не нужен, если команда выполняется из корня репозитория
         run: go work sync
 
+      - name: Go fmt/imports check
+        run: |
+          go install golang.org/x/tools/cmd/goimports@latest
+          if ! goimports -l .; then
+            echo "::error file=.::Go files not formatted with goimports or imports are unorganized. Please run 'goimports -w .' on your local machine."
+            exit 1
+          fi
+
       - name: Run tests in goldentest module
         working-directory: ./goldentest # Указываем путь к модулю goldentest
         run: go test -v ./
